# Generated by Django 2.1.7 on 2019-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('contactNo', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('rollNumber', models.IntegerField()),
                ('guardianName', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
